% tic,sudoku_comp(tbc1),toc;
% tic,sudoku_comp(tbc2),toc;
% tic,sudoku_comp(tbc3),toc;
% tic,sudoku_comp(tbc4),toc;
% tic,sudoku_comp(tbc5),toc;
% tic,sudoku_comp(tbc6),toc;
% tic,sudoku_comp(tbc7),toc;
% tic,sudoku_comp(comp1),toc;
% tic,sudoku_comp(comp2),toc;
